@echo off
title SlickAlex .NET 10 SDK Updater
setlocal enabledelayedexpansion

:: --- PATHS ---
set "COMPILER_DIR=%~dp0Compiler"
set "VERSION_FILE=%COMPILER_DIR%\dotnet_version.txt"
set "TEMP_DIR=%~dp0TempDotNet"

if not exist "%COMPILER_DIR%" mkdir "%COMPILER_DIR%"
if not exist "%TEMP_DIR%" mkdir "%TEMP_DIR%"

echo --- SLICKALEX .NET 10 SDK UPDATER ---

:: --- GET LATEST SDK VERSION AND DOWNLOAD URL ---
:: We are now searching for the '.zip' file instead of the '.exe' for a true local install.
powershell -NoProfile -ExecutionPolicy Bypass -Command "$json = Invoke-RestMethod 'https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/10.0/releases.json'; $latestVer = $json.releases[0].sdk.version; $fileUrl = ($json.releases[0].sdk.files | Where-Object { $_.rid -eq 'win-x64' -and $_.name -like '*.zip' }).url; Write-Output $latestVer; Write-Output $fileUrl" > "%TEMP_DIR%\latest_info.txt"

:: Read the two lines generated by PowerShell into variables
<"%TEMP_DIR%\latest_info.txt" (
  set /p LATEST_VERSION=
  set /p SDK_URL=
)

:: Strip any accidental spaces from the variable just to be safe
set "LATEST_VERSION=%LATEST_VERSION: =%"

if "%LATEST_VERSION%"=="" (
    echo ERROR: Failed to fetch the latest .NET 10 version. Check your internet connection.
    pause
    exit /b
)

:: --- CHECK IF ALREADY INSTALLED ---
if exist "%VERSION_FILE%" (
    set /p CURRENT_VERSION=<"%VERSION_FILE%"
    :: Strip spaces from the saved version too
    set "CURRENT_VERSION=!CURRENT_VERSION: =!"
    
    if "!CURRENT_VERSION!"=="%LATEST_VERSION%" (
        echo You already have the latest .NET 10 SDK: %LATEST_VERSION%
        rd /s /q "%TEMP_DIR%"
        pause
        exit /b
    )
)

echo Latest .NET 10 SDK: %LATEST_VERSION%
echo Downloading SDK Zip...

:: --- DOWNLOAD SDK ZIP ---
powershell -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest -Uri '%SDK_URL%' -OutFile '%TEMP_DIR%\dotnet-sdk.zip'"

if not exist "%TEMP_DIR%\dotnet-sdk.zip" (
    echo ERROR: Failed to download the SDK zip.
    pause
    exit /b
)

:: --- EXTRACT INTO LOCAL FOLDER ---
echo Extracting SDK into %COMPILER_DIR%... (This might take a moment)
powershell -NoProfile -ExecutionPolicy Bypass -Command "Expand-Archive -Path '%TEMP_DIR%\dotnet-sdk.zip' -DestinationPath '%COMPILER_DIR%' -Force"

:: --- SAVE VERSION ---
:: We put the redirect symbol at the front to guarantee absolutely no trailing spaces are saved
> "%VERSION_FILE%" echo %LATEST_VERSION%

:: --- CLEAN UP ---
rd /s /q "%TEMP_DIR%"

echo SUCCESS: .NET 10 SDK updated to %LATEST_VERSION%
pause